# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NavigationTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NavigationTest

	pod 'MXParallaxHeader', :git => 'https://github.com/youla-dev/MXParallaxHeader.git'
  pod 'MXSegmentedPager', :git => 'https://github.com/youla-dev/MXSegmentedPager.git', :branch => '88z'
  pod 'HMSegmentedControl', :git => 'https://github.com/youla-dev/HMSegmentedControl', :branch => 'accessibility'
  #Использую свой форк. Но я в нем ничего не менял. Просто автор уже исправил косяк, не не сделал релиз. Убрать эту строчку, когда обновятся MXSegmentedPager и MXParallaxHeader и они будут использовать новую версию MXPagerView
  pod 'MXPagerView', '= 0.1.3'
  pod 'PinLayout', '~> 1.8.7'


end
